### ISSUE TITLE
"GITHUB_TOKEN not set" error when running with act

### ISSUE THREAD

**Issue by kirrg001** [taiki-e/create-gh-release-action#14]
Hi there!

I am using [`act`](https://github.com/nektos/act) to test the GH action locally.

```sh 
act push -e eventpath.json -s GH_PAT=TEST
```

release.yml

```
name: create-gh-release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*      

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          changelog: CHANGELOG.md
          draft: true
```

I am getting an error

> ❗  ::error::GITHUB_TOKEN not set

I am unable to use a custom secret variable name for my token and pass it into `taiki-e/create-gh-release-action@v1`.

Any idea?

Thanks :)
