### ISSUE TITLE
Action fails with `GITHUB_OUTPUT: unbound variable` but release is created

### ISSUE THREAD

**Issue by avsaase** [taiki-e/create-gh-release-action#17]
I'm running this action on a self-hosted MacOS runner and I'm getting this error when I try to make a release. 

```
/Users/alexander.vansaase/dev/actions-runner/_work/_actions/taiki-e/create-gh-release-action/v1/main.sh: line 118: GITHUB_OUTPUT: unbound variable
Error: Command failed: bash --noprofile --norc /Users/alexander.vansaase/dev/actions-runner/_work/_actions/taiki-e/create-gh-release-action/v1/main.sh
```

Even though the action fails, the release is created.

Here's my `release.yaml`:
```
name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qbn
          target: ${{ matrix.target }}
          build_tool: cargo
          token: ${{ secrets.GITHUB_TOKEN }}
          zip: all
          tar: none
```
