### ISSUE TITLE
Promoting draft release

### ISSUE THREAD

**Issue by aymericbeaumet** [taiki-e/create-gh-release-action#25]
I'm trying to implement the following workflow:

1. Create a draft release
2. Build and publish to the registries
3. Publish the release by promoting the draft as the final release

I've tried the following, but the draft release is overriden:

```yaml
jobs:
  begin-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  # other jobs

  finish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
```

Do you have any suggestion as to how to approach this draft -> publish promotion?

**Comment by taiki-e** [comment]
Currently, this action only supports creating a new release or overwriting an existing release (https://github.com/taiki-e/create-gh-release-action/issues/5), but I'm okay with adding support for updating an existing release.

That said, the following single command should probably be enough to do this:

```yaml
- run: gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See also [GitHub CLI docs](https://cli.github.com/manual/gh_release_edit).
